name: example
channels:
  - conda-forge
dependencies:
  - tensorflow=2.1.0
  - cudatoolkit=10.1
  - cudnn=7.6
  - matplotlib>=3.3.1
  - numpy>=1.19.1
  - flask>=1.1.2
  - protobuf=3.19.0
  - gunicorn=20.1.0
  - psycopg2=2.9.4
